export const robots = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    email: "Sincere@april.biz",
  },
  {
    id: 2,
    name: "Ervin Howell",
    username: "Antonette",
    email: "Shanna@melissa.tv",
  },
  {
    id: 3,
    name: "Clementine Bauch",
    username: "Samantha",
    email: "Nathan@yesenia.net",
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    username: "Karianne",
    email: "Julianne.OConner@kory.org",
  },
  {
    id: 5,
    name: "Chelsey Dietrich",
    username: "Kamren",
    email: "Lucio_Hettinger@annie.ca",
  },
  {
    id: 6,
    name: "Mrs. Dennis Schulist",
    username: "Leopoldo_Corkery",
    email: "Karley_Dach@jasper.info",
  },
  {
    id: 7,
    name: "Kurtis Weissnat",
    username: "Elwyn.Skiles",
    email: "Telly.Hoeger@billy.biz",
  },
  {
    id: 8,
    name: "Nicholas Runolfsdottir V",
    username: "Maxime_Nienow",
    email: "Sherwood@rosamond.me",
  },
  {
    id: 9,
    name: "Glenna Reichert",
    username: "Delphine",
    email: "Chaim_McDermott@dana.io",
  },
  {
    id: 10,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
  },

  {
    id: 11,
    name: "Leanne Graham",
    username: "Bret",
    email: "ana.titi@tina.us",
  },
  {
    id: 12,
    name: "Ervin Howell",
    username: "Antonette",
    email: "iotlol@gmail.com",
  },
  {
    id: 13,
    name: "Clementine Bauch",
    username: "Samantha",
    email: "clementine.bauch@example.com",
  },
  {
    id: 14,
    name: "Patricia Lebsack",
    username: "Karianne",
    email: "patricia.lebsack@example.com",
  },
  {
    id: 15,
    name: "Chelsey Dietrich",
    username: "Kamren",
    email: "chelsey.dietrich@example.com",
  },
  {
    id: 16,
    name: "Dennis Schulist",
    username: "Leopoldo_Corkery",
    email: "dennis.schulist@example.com",
  },
  {
    id: 17,
    name: "Kurtis Weissnat",
    username: "Elwyn.Skiles",
    email: "kurtis.weissnat@example.com",
  },
  {
    id: 18,
    name: "Nicholas Runolfsdottir V",
    username: "Maxime_Nienow",
    email: "nicholas.runolfsdottir@example.com",
  },
  {
    id: 19,
    name: "Glenna Reichert",
    username: "Delphine",
    email: "glenna.reichert@example.com",
  },
  {
    id: 20,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "clementina.dubuque@example.com",
  },
  {
    id: 21,
    name: "Leanne Graham",
    username: "Bret",
    email: "leanne.graham@example.com",
  },
  {
    id: 22,
    name: "Mrs. Dennis Schulist",
    username: "Karley_Dach",
    email: "dennis.schulist@example.com",
  },
  {
    id: 23,
    name: "Ervin Howell",
    username: "Antonette",
    email: "ervin.howell@example.com",
  },
  {
    id: 24,
    name: "Glenna Reichert",
    username: "Delphine",
    email: "glenna.reichert@example.com",
  },
  {
    id: 25,
    name: "Kurtis Weissnat",
    username: "Elwyn.Skiles",
    email: "kurtis.weissnat@example.com",
  },
  {
    id: 26,
    name: "Nicholas Runolfsdottir V",
    username: "Maxime_Nienow",
    email: "nicholas.runolfsdottir@example.com",
  },
  {
    id: 27,
    name: "Glenna Reichert",
    username: "Delphine",
    email: "glenna.reichert@example.com",
  },
  {
    id: 28,
    name: "Patricia Lebsack",
    username: "Karianne",
    email: "patricia@gmail.com",
  },
  {
    id: 29,
    name: "Chelsey Dietrich",
    username: "Kamren",
    email: "chelsey@gmail.com",
  },
  {
    id: 30,
    name: "Dennis Schulist",
    username: "Leopoldo_Corkery",
    email: "dennis@gmail.com",
  },
];
